# Generated by Django 5.1.4 on 2025-06-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flight_number", models.CharField(max_length=10, unique=True)),
                ("departure_city", models.CharField(max_length=50)),
                ("arrival_city", models.CharField(max_length=50)),
                ("departure_time", models.DateTimeField()),
                ("arrival_time", models.DateTimeField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
                ),
                ("capacity", models.IntegerField()),
                ("available_seats", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("full", "Full"),
                            ("departed", "Departed"),
                            ("canceled", "Canceled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("aircraft_type", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
