# Generated by Django 5.1.4 on 2025-06-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flight", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="flight",
            options={"verbose_name": "航班", "verbose_name_plural": "航班"},
        ),
        migrations.AlterField(
            model_name="flight",
            name="aircraft_type",
            field=models.CharField(max_length=50, verbose_name="飞机型号"),
        ),
        migrations.AlterField(
            model_name="flight",
            name="arrival_city",
            field=models.CharField(max_length=50, verbose_name="到达城市"),
        ),
        migrations.AlterField(
            model_name="flight",
            name="arrival_time",
            field=models.DateTimeField(verbose_name="到达时间"),
        ),
        migrations.AlterField(
            model_name="flight",
            name="available_seats",
            field=models.IntegerField(verbose_name="剩余座位数"),
        ),
        migrations.AlterField(
            model_name="flight",
            name="capacity",
            field=models.IntegerField(verbose_name="总座位数"),
        ),
        migrations.AlterField(
            model_name="flight",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="flight",
            name="departure_city",
            field=models.CharField(max_length=50, verbose_name="出发城市"),
        ),
        migrations.AlterField(
            model_name="flight",
            name="departure_time",
            field=models.DateTimeField(verbose_name="起飞时间"),
        ),
        migrations.AlterField(
            model_name="flight",
            name="discount",
            field=models.DecimalField(
                decimal_places=2, default=1.0, max_digits=3, verbose_name="折扣率"
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="flight_number",
            field=models.CharField(max_length=10, unique=True, verbose_name="航班号"),
        ),
        migrations.AlterField(
            model_name="flight",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="票价"
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "已计划"),
                    ("full", "已满"),
                    ("departed", "已起飞"),
                    ("canceled", "已取消"),
                ],
                default="scheduled",
                max_length=20,
                verbose_name="航班状态",
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
    ]
