# Generated by Django 5.1.4 on 2025-06-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flight", "0002_alter_flight_options_alter_flight_aircraft_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="seat_rows",
            field=models.IntegerField(default=0, verbose_name="座位排数"),
        ),
        migrations.AddField(
            model_name="flight",
            name="seats_per_row",
            field=models.IntegerField(default=0, verbose_name="每排座位数"),
        ),
    ]
