# Generated by Django 5.1.4 on 2025-06-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flight", "0003_flight_seat_rows_flight_seats_per_row"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="is_international",
            field=models.BooleanField(default=False, verbose_name="是否国际航班"),
        ),
    ]
