# Generated by Django 5.1.4 on 2025-06-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flight", "0004_flight_is_international"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="airline_name",
            field=models.CharField(default="", max_length=50, verbose_name="航空公司"),
        ),
    ]
