# Generated by Django 5.1.4 on 2025-11-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0005_flight_airline_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['departure_city', 'arrival_city', 'departure_time'], name='flight_flig_departu_74c324_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['status', 'departure_time'], name='flight_flig_status_c4505c_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['departure_time'], name='flight_flig_departu_855d3c_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['price'], name='flight_flig_price_c1f11d_idx'),
        ),
    ]
