# Generated by Django 5.1.4 on 2026-01-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0006_flight_flight_flig_departu_74c324_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='baggage_allowance',
            field=models.IntegerField(default=20, verbose_name='行李额度(kg)'),
        ),
        migrations.AddField(
            model_name='flight',
            name='meal_service',
            field=models.BooleanField(default=True, verbose_name='提供餐食'),
        ),
    ]
