# Generated by Django 5.1.4 on 2026-01-04 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0007_add_meal_service_and_baggage_allowance'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='entertainment',
            field=models.BooleanField(default=False, verbose_name='提供娱乐系统'),
        ),
        migrations.AddField(
            model_name='flight',
            name='power_outlet',
            field=models.BooleanField(default=False, verbose_name='提供电源插座'),
        ),
        migrations.AddField(
            model_name='flight',
            name='wifi',
            field=models.BooleanField(default=False, verbose_name='提供WiFi'),
        ),
    ]
