# Generated by Django 5.1.4 on 2025-06-26 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="城市名称")),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="城市代码"
                    ),
                ),
                (
                    "country",
                    models.CharField(default="中国", max_length=100, verbose_name="国家"),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="经度",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="纬度",
                    ),
                ),
            ],
            options={
                "verbose_name": "城市",
                "verbose_name_plural": "城市",
            },
        ),
        migrations.CreateModel(
            name="WeatherCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperature", models.IntegerField(verbose_name="温度(°C)")),
                ("description", models.CharField(max_length=100, verbose_name="天气描述")),
                ("humidity", models.IntegerField(verbose_name="湿度(%)")),
                (
                    "wind_speed",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="风速(m/s)"
                    ),
                ),
                ("icon", models.CharField(max_length=100, verbose_name="图标代码")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.city",
                        verbose_name="城市",
                    ),
                ),
            ],
            options={
                "verbose_name": "天气缓存",
                "verbose_name_plural": "天气缓存",
            },
        ),
        migrations.CreateModel(
            name="PopularRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="基础价格"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2, default=1.0, max_digits=3, verbose_name="折扣率"
                    ),
                ),
                ("popularity", models.IntegerField(default=0, verbose_name="受欢迎程度")),
                (
                    "from_city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes_from",
                        to="core.city",
                        verbose_name="出发城市",
                    ),
                ),
                (
                    "to_city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes_to",
                        to="core.city",
                        verbose_name="到达城市",
                    ),
                ),
            ],
            options={
                "verbose_name": "热门航线",
                "verbose_name_plural": "热门航线",
                "unique_together": {("from_city", "to_city")},
            },
        ),
    ]
