# Generated by Django 5.1.4 on 2025-11-21 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_city_weathercache_popularroute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='航空公司名称')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='航空公司代码')),
                ('logo_url', models.URLField(blank=True, null=True, verbose_name='Logo URL')),
            ],
            options={
                'verbose_name': '航空公司',
                'verbose_name_plural': '航空公司',
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='机场名称')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='机场代码')),
                ('terminal', models.CharField(default='T1', max_length=10, verbose_name='航站楼')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.city', verbose_name='所属城市')),
            ],
            options={
                'verbose_name': '机场',
                'verbose_name_plural': '机场',
            },
        ),
    ]
