# Generated by Django 5.1.4 on 2025-11-28 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_airline_airport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeatherCache',
        ),
    ]
