# Generated by Django 5.1.4 on 2026-01-02 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_weathercache'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('site', '站点信息'), ('business', '业务规则')], max_length=20, verbose_name='分类')),
                ('key', models.CharField(max_length=100, verbose_name='配置键')),
                ('value', models.TextField(verbose_name='配置值')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='描述')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '系统设置',
                'verbose_name_plural': '系统设置',
                'unique_together': {('category', 'key')},
            },
        ),
        migrations.CreateModel(
            name='SettingsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_value', models.TextField(verbose_name='旧值')),
                ('new_value', models.TextField(verbose_name='新值')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.systemsettings', verbose_name='设置项')),
            ],
            options={
                'verbose_name': '设置变更历史',
                'verbose_name_plural': '设置变更历史',
                'ordering': ['-changed_at'],
            },
        ),
    ]
