# Generated by Django 5.2.1 on 2025-06-26 02:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="地址"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars/", verbose_name="用户头像"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "男"), ("female", "女"), ("other", "其他")],
                max_length=10,
                null=True,
                verbose_name="性别",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="id_card",
            field=models.CharField(
                blank=True, max_length=18, null=True, verbose_name="身份证号码"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="real_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="真实姓名"
            ),
        ),
    ]
