# Generated by Django 5.1.4 on 2025-11-21 09:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_address_user_avatar_user_gender_user_id_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='id_card',
            field=models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='身份证号码格式不正确', regex='^[1-9]\\d{5}(18|19|20)\\d{2}((0[1-9])|(1[0-2]))(([0-2][1-9])|10|20|30|31)\\d{3}[0-9Xx]$')], verbose_name='身份证号码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_card',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='身份证号码格式不正确', regex='^[1-9]\\d{5}(18|19|20)\\d{2}((0[1-9])|(1[0-2]))(([0-2][1-9])|10|20|30|31)\\d{3}[0-9Xx]$')], verbose_name='身份证号码'),
        ),
    ]
