# Generated by Django 5.2.1 on 2025-06-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="total_amount",
            new_name="total_price",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="passenger",
        ),
        migrations.AddField(
            model_name="order",
            name="contact_email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="联系人邮箱"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="contact_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="联系人姓名"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="contact_phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="联系人电话"
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="cabin_class",
            field=models.CharField(
                choices=[("economy", "经济舱"), ("business", "商务舱"), ("first", "头等舱")],
                default="economy",
                max_length=20,
                verbose_name="舱位等级",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="passenger_id_number",
            field=models.CharField(
                default="000000000000000000", max_length=30, verbose_name="证件号码"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ticket",
            name="passenger_id_type",
            field=models.CharField(default="身份证", max_length=20, verbose_name="证件类型"),
        ),
        migrations.AddField(
            model_name="ticket",
            name="passenger_name",
            field=models.CharField(
                default="000000000000000000", max_length=100, verbose_name="乘客姓名"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待支付"),
                    ("paid", "已支付"),
                    ("completed", "已完成"),
                    ("canceled", "已取消"),
                ],
                default="pending",
                max_length=20,
                verbose_name="订单状态",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="ticket_number",
            field=models.CharField(
                blank=True, max_length=15, null=True, unique=True, verbose_name="机票编号"
            ),
        ),
    ]
