# Generated by Django 5.1.4 on 2025-11-21 09:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_total_amount_order_total_price_and_more'),
        ('flight', '0006_flight_flight_flig_departu_74c324_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='booking_ord_user_id_a3a5d6_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='booking_ord_status_b50f67_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='booking_ord_created_1f7077_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['flight', 'status'], name='booking_tic_flight__e9ec37_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['order', 'status'], name='booking_tic_order_i_f73b35_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['passenger_id_number'], name='booking_tic_passeng_2888cb_idx'),
        ),
    ]
