# Generated by Django 5.1.4 on 2026-01-01 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_order_booking_ord_user_id_a3a5d6_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='boarding_pass_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='登机牌编号'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='checked_in',
            field=models.BooleanField(default=False, verbose_name='是否已值机'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='值机时间'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='gate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='登机口'),
        ),
    ]
