# Generated by Django 5.1.4 on 2026-01-02 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_add_checkin_fields'),
        ('flight', '0006_flight_flight_flig_departu_74c324_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='支付截止时间'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('valid', '有效'), ('refunded', '已退票'), ('used', '已使用'), ('rescheduled', '已改签'), ('canceled', '已取消')], default='valid', max_length=20, verbose_name='票务状态'),
        ),
        migrations.CreateModel(
            name='RescheduleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_difference', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='差价')),
                ('reschedule_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='改签手续费')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='改签时间')),
                ('new_flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_to_logs', to='flight.flight', verbose_name='新航班')),
                ('new_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_to_logs', to='booking.ticket', verbose_name='新机票')),
                ('original_flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_from_logs', to='flight.flight', verbose_name='原航班')),
                ('original_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_from_logs', to='booking.ticket', verbose_name='原机票')),
            ],
            options={
                'verbose_name': '改签记录',
                'verbose_name_plural': '改签记录',
                'indexes': [models.Index(fields=['original_ticket'], name='booking_res_origina_7ccd2e_idx'), models.Index(fields=['new_ticket'], name='booking_res_new_tic_d90b58_idx'), models.Index(fields=['created_at'], name='booking_res_created_0b758f_idx')],
            },
        ),
    ]
