# Generated by Django 5.1.4 on 2026-01-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_order_expires_at_alter_ticket_status_reschedulelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='seat_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='座位号（值机时分配）'),
        ),
    ]
