"""
Django settings for iFly project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import mimetypes
import os
from datetime import timedelta
from pathlib import Path

# 项目路径
BASE_DIR = Path(__file__).resolve().parent.parent

# 密钥配置，用于加密
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-lk0(ob9&$+3#ka64^@s%#vmz687=^2a#qx-mfoc#32!e-!nhp1')

# 调试模式
DEBUG = True

# 域名访问权限
ALLOWED_HOSTS = ["*"]

# App列表
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    
    # 第三方应用
    "rest_framework",
    "corsheaders",
    "django_filters",
    "drf_yasg",
    "coreapi",
    "rest_framework_simplejwt",
    "debug_toolbar",
    "rest_framework.authtoken",
    
    # 自定义应用 - 核心应用
    "accounts",
    "flight",
    "booking",
    "payments",
    "notifications",
    "analytics",
    "core",
    "user_messages",  # 消息应用
    "admin_api",  # 管理员API
]

# 中间件列表
MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # CORS中间件放在最前面
    "debug_toolbar.middleware.DebugToolbarMiddleware", 
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.http.ConditionalGetMiddleware",
    'core.middleware.SystemLogMiddleware',  # 系统操作日志中间件
    'core.middleware.FlightStatusUpdateMiddleware',  # 航班状态自动更新
]

# debug-toolbar 中间件
DEBUG_TOOLBAR_PANELS = [
    'debug_toolbar.panels.versions.VersionsPanel',
    'debug_toolbar.panels.timer.TimerPanel',
    'debug_toolbar.panels.settings.SettingsPanel',
    'debug_toolbar.panels.headers.HeadersPanel',
    'debug_toolbar.panels.request.RequestPanel',
    'debug_toolbar.panels.sql.SQLPanel',
    'debug_toolbar.panels.staticfiles.StaticFilesPanel',
    'debug_toolbar.panels.templates.TemplatesPanel',
    'debug_toolbar.panels.cache.CachePanel',
    'debug_toolbar.panels.signals.SignalsPanel',
    'debug_toolbar.panels.logging.LoggingPanel',
    'debug_toolbar.panels.redirects.RedirectsPanel',
]

# 允许在测试时跳过 debug_toolbar 检查
DEBUG_TOOLBAR_CONFIG = {
    'IS_RUNNING_TESTS': False,
}

# 允许访问 Django 开发服务器的 IP 地址
INTERNAL_IPS = ['127.0.0.1']

# 路由配置
ROOT_URLCONF = "iFly.urls"

# 模板配置
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# WSGI配置
WSGI_APPLICATION = "iFly.wsgi.application"

# 数据库配置
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# 密码验证器
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# 配置 REST framework
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 8,
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '1000/hour',  # 增加匿名用户的请求限制
        'user': '1000/hour'
    },
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ]
}

# 测试环境禁用限流
import sys
if 'test' in sys.argv:
    REST_FRAMEWORK['DEFAULT_THROTTLE_CLASSES'] = []
    REST_FRAMEWORK['DEFAULT_THROTTLE_RATES'] = {}

# 配置 JWT
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=100),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}

# 允许所有来源（测试时使用，生产环境要更安全）
CORS_ALLOW_ALL_ORIGINS = True

# 允许所有请求头
CORS_ALLOW_ALL_HEADERS = True

# 允许所有方法
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# 允许跨域携带认证信息（如果使用 JWT / Session 认证）
CORS_ALLOW_CREDENTIALS = True

# 语言配置
LANGUAGE_CODE = "zh-Hans"

# 时区配置
TIME_ZONE = "Asia/Shanghai"

# 国际化配置
USE_I18N = True

# 本地化配置
USE_TZ = True

# 静态资源路径
STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# 默认主键类型
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# 自定义用户模型
AUTH_USER_MODEL = "accounts.User"

# 媒体文件存储根目录
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# 媒体文件的 URL 前缀
MEDIA_URL = '/media/'

# 静态文件存储目录
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# 设置最大上传文件大小（单位为字节）
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB

# 允许上传的图片类型
ALLOWED_AVATAR_TYPES = ['image/jpeg', 'image/png', 'image/gif']

# 最大头像文件大小（2MB）
MAX_AVATAR_SIZE = 2 * 1024 * 1024

# 启用 Pygments 高亮
MARKDOWNX_USE_PYGMENTS = True
MARKDOWNX_MARKDOWN_EXTENSIONS = ['extra', 'codehilite', 'fenced_code']
MARKDOWNX_PYGMENTS_STYLE = 'default'  # 选择代码高亮主题

# HTTP 响应头
X_FRAME_OPTIONS = "SAMEORIGIN"

# 禁用系统检查
SILENCED_SYSTEM_CHECKS = ["security.W019"]

# 处理 JavaScript 文件时使用正确的 MIME 类型
mimetypes.add_type("application/javascript", ".js")

# CORS 配置 - 开发环境使用
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

# 日志配置
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
            'maxBytes': 1024*1024*5,  # 5MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'error.log'),
            'maxBytes': 1024*1024*5,  # 5MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['error_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'accounts': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'flight': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'booking': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
