# Generated by Django 5.1.4 on 2025-06-27 02:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notif_type",
            field=models.CharField(
                choices=[
                    ("system", "系统通知"),
                    ("order", "订单更新"),
                    ("flight", "航班变动"),
                    ("payment", "支付通知"),
                    ("refund", "退款通知"),
                    ("info", "信息"),
                    ("warning", "警告"),
                    ("alert", "警报"),
                ],
                default="system",
                max_length=20,
                verbose_name="消息类型",
            ),
        ),
    ]
